name=input("insert your name")
weight=float(input("insert yout weight"))
height=float(input("insert your height"))
imc=weight/(height*height)
print(name," has ", str(height), " of height " , " your weight is ", str(weight) ," and your imc is ", str(imc))